using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.Netcode;

public class PlayerUIManager : MonoBehaviour
{
    public static PlayerUIManager instance;

    [Header("NETWORK JOIN")]
    [SerializeField] bool startGameAsClient;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else {
            Destroy(gameObject);
        }
    }

    private void Start()
    {
        DontDestroyOnLoad(gameObject);
    }

    private void Update()
    {
        if (startGameAsClient)
        {
            startGameAsClient = false;
            // MUST FIRST SHUTDOWN NETWORK AS HOST, TO START NETWORK AS CLIENT
            NetworkManager.Singleton.Shutdown();
            // WE THEN START NETWORK AS CLIENT
            NetworkManager.Singleton.StartClient();
        }
    }
}
